# Generated by Django 5.2.10 on 2026-01-19 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance'), ('energy', 'Increase Energy'), ('general_health', 'General Health')], max_length=20)),
                ('diet_type', models.CharField(choices=[('balanced', 'Balanced Diet'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('keto', 'Keto'), ('paleo', 'Paleo'), ('gluten_free', 'Gluten Free'), ('mediterranean', 'Mediterranean')], max_length=20)),
                ('daily_calories', models.IntegerField(default=2000)),
                ('allergies', models.TextField(blank=True, help_text='Comma-separated list of allergies')),
                ('dislikes', models.TextField(blank=True, help_text='Comma-separated list of foods to avoid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Health Goals',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('calories', models.IntegerField()),
                ('protein_g', models.FloatField(default=0)),
                ('carbs_g', models.FloatField(default=0)),
                ('fat_g', models.FloatField(default=0)),
                ('prep_time_min', models.IntegerField(default=15)),
                ('ingredients', models.TextField(help_text='Comma-separated ingredients')),
                ('instructions', models.TextField()),
                ('diet_types', models.CharField(blank=True, help_text='Comma-separated diet types (e.g., vegan, keto)', max_length=100)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
            ],
            options={
                'ordering': ['meal_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('health_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.healthgoal')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.CharField(help_text='e.g., 2 kg, 1 bunch, 1 liter', max_length=100)),
                ('category', models.CharField(choices=[('produce', 'Produce'), ('dairy', 'Dairy'), ('meat', 'Meat & Fish'), ('grains', 'Grains & Cereals'), ('pantry', 'Pantry'), ('frozen', 'Frozen'), ('beverages', 'Beverages')], max_length=50)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('purchased', models.BooleanField(default=False)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_items', to='myapp.mealplan')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(choices=[(1, 'Day 1'), (2, 'Day 2'), (3, 'Day 3'), (4, 'Day 4'), (5, 'Day 5'), (6, 'Day 6'), (7, 'Day 7')])),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='myapp.mealplan')),
                ('breakfast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakfast_meals', to='myapp.recipe')),
                ('dinner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dinner_meals', to='myapp.recipe')),
                ('lunch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lunch_meals', to='myapp.recipe')),
                ('snack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snack_meals', to='myapp.recipe')),
            ],
            options={
                'ordering': ['meal_plan', 'day_number'],
                'unique_together': {('meal_plan', 'day_number')},
            },
        ),
    ]
